"use client";

import Link from "next/link";
import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  ArrowLeft, CalendarDays, Check, Circle, ExternalLink, File, GripVertical, Link2, ListTodo,
  MessageSquare, MoreHorizontal, Plus, Send, Upload, UserRoundCog, Users,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { fileToDataUrl } from "@/lib/file-to-data-url";
import { initials } from "@/utils/format";
import type { ProjectWorkspaceRecord } from "@/types/project-management";
import {
  addProjectFileAction, addProjectLinkAction, archiveProjectNoteAction, archiveProjectTaskAction,
  createMilestoneAction, createProjectConversationAction, createProjectNoteAction, createProjectTaskAction,
  reorderMilestonesAction, sendProjectMessageAction, toggleChecklistItemAction, updateMilestoneStatusAction,
  updateProjectNoteAction, updateProjectTaskAction, updateProjectTaskStatusAction, updateProjectTeamAction,
} from "@/services/project-management";

const TASK_COLUMNS = [
  { value: "NOT_STARTED", label: "To Do", color: "bg-slate-500" },
  { value: "IN_PROGRESS", label: "In Progress", color: "bg-blue-500" },
  { value: "REVIEW", label: "Review", color: "bg-amber-500" },
  { value: "COMPLETED", label: "Completed", color: "bg-emerald-500" },
] as const;

const MILESTONE_LABEL = { NOT_STARTED: "Upcoming", IN_PROGRESS: "Current", COMPLETED: "Completed", DELAYED: "Delayed" } as const;

export function ProjectWorkspace({ project, backHref }: { project: ProjectWorkspaceRecord; backHref: string }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [dialog, setDialog] = useState<null | "task" | "milestone" | "link" | "file" | "note" | "conversation" | "team">(null);
  const [selectedConversationId, setSelectedConversationId] = useState(project.conversations[0]?.id ?? "");
  const selectedConversation = project.conversations.find((item) => item.id === selectedConversationId) ?? project.conversations[0];
  const [message, setMessage] = useState("");
  const [taskForm, setTaskForm] = useState<{ title: string; description: string; dueDate: string; priority: "LOW" | "MEDIUM" | "HIGH"; status: "NOT_STARTED" | "IN_PROGRESS" | "REVIEW" | "COMPLETED"; assigneeIds: string[]; checklist: string }>({ title: "", description: "", dueDate: new Date().toISOString().slice(0, 10), priority: "MEDIUM", status: "NOT_STARTED", assigneeIds: [], checklist: "" });
  const [editingTaskId, setEditingTaskId] = useState("");
  const [milestoneForm, setMilestoneForm] = useState({ title: "", description: "", startDate: "", dueDate: new Date().toISOString().slice(0, 10), ownerId: "" });
  const [resourceForm, setResourceForm] = useState({ title: "", url: "", note: "" });
  const [fileForm, setFileForm] = useState<{ title: string; note: string; file: globalThis.File | null }>({ title: "", note: "", file: null });
  const [noteForm, setNoteForm] = useState({ id: "", title: "", content: "" });
  const [conversationForm, setConversationForm] = useState({ name: "", participantIds: [] as string[], taskId: "" });
  const [teamForm, setTeamForm] = useState({ headUserId: project.head?.id ?? "", memberIds: project.members.map((member) => member.id) });
  const fileInput = useRef<HTMLInputElement>(null);

  const refresh = () => startTransition(() => router.refresh());
  const run = async (promise: Promise<{ success: boolean; error?: string }>, success: string) => {
    const result = await promise;
    if (!result.success) return toast.error(result.error || "Something went wrong.");
    toast.success(success); setDialog(null); refresh();
  };

  async function createTask() {
    const input = { ...taskForm, checklist: taskForm.checklist.split("\n").map((item) => item.trim()).filter(Boolean) };
    await run(editingTaskId ? updateProjectTaskAction(project.id, editingTaskId, input) : createProjectTaskAction(project.id, input), editingTaskId ? "Task updated" : "Task created");
    setEditingTaskId("");
    setTaskForm({ title: "", description: "", dueDate: new Date().toISOString().slice(0, 10), priority: "MEDIUM", status: "NOT_STARTED", assigneeIds: [], checklist: "" });
  }

  async function uploadFile() {
    if (!fileForm.file) return toast.error("Choose a file first.");
    const dataUrl = await fileToDataUrl(fileForm.file);
    await run(addProjectFileAction(project.id, { title: fileForm.title, note: fileForm.note, fileName: fileForm.file.name, mimeType: fileForm.file.type, sizeBytes: fileForm.file.size, dataUrl }), "File uploaded");
  }

  async function sendMessage() {
    if (!selectedConversation || !message.trim()) return;
    const content = message; setMessage("");
    const result = await sendProjectMessageAction(project.id, selectedConversation.id, content);
    if (!result.success) toast.error(result.error); else refresh();
  }

  function editNote(note: ProjectWorkspaceRecord["notes"][number]) {
    setNoteForm({ id: note.id, title: note.title, content: note.content }); setDialog("note");
  }

  const upcomingTasks = project.tasks.filter((task) => task.status !== "COMPLETED").slice(0, 4);
  const recentResources = project.resources.slice(0, 4);
  const conversationTitle = (conversation: ProjectWorkspaceRecord["conversations"][number]) => conversation.name || conversation.participants.filter((p) => p.id !== project.currentUserId).map((p) => p.name).join(", ") || "Project conversation";

  return (
    <div className="space-y-6">
      <div><Link href={backHref} className="mb-4 inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back to projects</Link>
        <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">{project.clientName}</Badge><Badge className="border-0 bg-emerald-500/10 text-emerald-700">{project.status.toLowerCase()}</Badge><Badge variant="outline">{project.priority.toLowerCase()} priority</Badge></div><h1 className="mt-2 text-2xl font-semibold tracking-tight">{project.name}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{project.description || "No project description yet."}</p></div>{project.canManage && <Button variant="outline" onClick={() => setDialog("team")}><UserRoundCog className="h-4 w-4" /> Manage Team</Button>}</div>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <MetaCard icon={CalendarDays} label="Timeline" value={`${date(project.startDate)} – ${date(project.expectedEndDate)}`} />
        <MetaCard icon={Users} label="Project head" value={project.head?.name || "Unassigned"} />
        <MetaCard icon={ListTodo} label="Tasks" value={`${project.completedTaskCount} of ${project.taskCount} complete`} />
        <div className="rounded-2xl border bg-card p-4"><div className="flex justify-between text-xs"><span className="text-muted-foreground">Overall progress</span><span className="font-semibold">{project.progress}%</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${project.progress}%` }} /></div><div className="mt-3 flex -space-x-2">{project.members.slice(0, 6).map((member) => <Avatar key={member.id} name={member.name} />)}</div></div>
      </div>

      <Tabs defaultValue="overview" className="space-y-5">
        <TabsList className="h-auto w-full justify-start overflow-x-auto rounded-xl border bg-card p-1">
          {[['overview','Overview'],['tasks','Tasks'],['timeline','Timeline'],['resources','Files & Links'],['notes','Notes'],['conversations','Conversations']].map(([value,label]) => <TabsTrigger key={value} value={value} className="shrink-0">{label}</TabsTrigger>)}
        </TabsList>

        <TabsContent value="overview"><div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="space-y-5"><Panel title="Upcoming tasks" action={project.canManage ? <Button size="sm" onClick={() => setDialog("task")}><Plus className="h-4 w-4" /> Add Task</Button> : undefined}>{upcomingTasks.length ? <div className="divide-y">{upcomingTasks.map((task) => <div key={task.id} className="flex items-center gap-3 py-3"><Circle className="h-4 w-4 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{task.title}</p><p className="text-xs text-muted-foreground">Due {date(task.dueDate)} · {task.assignees.map((a) => a.name).join(", ")}</p></div><Badge variant="outline">{task.status.replaceAll("_", " ").toLowerCase()}</Badge></div>)}</div> : <Empty text="No upcoming tasks." />}</Panel><Panel title="Recent files & links">{recentResources.length ? <div className="grid gap-2 sm:grid-cols-2">{recentResources.map((resource) => <ResourceRow key={resource.id} resource={resource} />)}</div> : <Empty text="No resources shared yet." />}</Panel></div><div className="space-y-5"><Panel title="Recent activity">{project.activities.length ? <div className="space-y-4">{project.activities.slice(0, 8).map((activity) => <div key={activity.id} className="flex gap-3"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-primary" /><div><p className="text-sm">{activity.detail}</p><p className="text-[11px] text-muted-foreground">{activity.actor.name} · {dateTime(activity.createdAt)}</p></div></div>)}</div> : <Empty text="No activity yet." />}</Panel><Panel title="Recent notes">{project.notes.slice(0, 3).map((note) => <button key={note.id} onClick={() => editNote(note)} className="mb-2 w-full rounded-xl bg-muted/40 p-3 text-left"><p className="text-sm font-medium">{note.title}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{note.content}</p></button>)}</Panel></div></div></TabsContent>

        <TabsContent value="tasks">
          <Panel title="Project tasks" description="Progress updates automatically roll up into overall project progress." action={project.canManage ? <Button onClick={() => { setEditingTaskId(""); setTaskForm({ title: "", description: "", dueDate: new Date().toISOString().slice(0, 10), priority: "MEDIUM", status: "NOT_STARTED", assigneeIds: [], checklist: "" }); setDialog("task"); }}><Plus className="h-4 w-4" /> New Task</Button> : undefined}>
            <div className="grid gap-4 xl:grid-cols-4">
              {TASK_COLUMNS.map((column) => <div key={column.value} className="rounded-xl bg-muted/35 p-3"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><span className={cn("h-2 w-2 rounded-full", column.color)} /><h3 className="text-xs font-semibold">{column.label}</h3></div><Badge variant="secondary">{project.tasks.filter((task) => task.status === column.value).length}</Badge></div><div className="space-y-2">{project.tasks.filter((task) => task.status === column.value).map((task) => <TaskCard key={task.id} task={task} canManage={project.canManage} onEdit={() => { setEditingTaskId(task.id); setTaskForm({ title: task.title, description: task.description || "", dueDate: task.dueDate.slice(0, 10), priority: task.priority, status: task.status === "OVERDUE" ? "NOT_STARTED" : task.status, assigneeIds: task.assignees.map((member) => member.id), checklist: task.checklist.map((item) => item.title).join("\n") }); setDialog("task"); }} onStatus={(status) => run(updateProjectTaskStatusAction(project.id, task.id, status), "Task updated")} onArchive={() => run(archiveProjectTaskAction(project.id, task.id), "Task archived")} onChecklist={(id) => run(toggleChecklistItemAction(project.id, id), "Checklist updated")} />)}</div></div>)}
            </div>
          </Panel>
        </TabsContent>

        <TabsContent value="timeline"><Panel title="Project flow" description="Milestones are ordered, owned, and fully editable in status." action={project.canManage ? <Button onClick={() => setDialog("milestone")}><Plus className="h-4 w-4" /> Add Milestone</Button> : undefined}><div className="mx-auto max-w-3xl">{project.milestones.length ? project.milestones.map((milestone, index) => <div key={milestone.id} className="group flex gap-4"><div className="flex flex-col items-center"><button disabled={!project.canManage || index === 0} onClick={() => { const ids = project.milestones.map((m) => m.id); [ids[index - 1], ids[index]] = [ids[index], ids[index - 1]]; run(reorderMilestonesAction(project.id, ids), "Timeline reordered"); }} className={cn("grid h-9 w-9 place-items-center rounded-full border-2 bg-card", milestone.status === "COMPLETED" ? "border-emerald-500 text-emerald-600" : milestone.status === "IN_PROGRESS" ? "border-primary text-primary" : "border-border text-muted-foreground")} title="Move this milestone earlier"><GripVertical className="h-4 w-4" /></button>{index < project.milestones.length - 1 && <div className={cn("h-20 w-0.5", milestone.status === "COMPLETED" ? "bg-emerald-500" : "bg-border")} />}</div><div className="mb-5 min-w-0 flex-1 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{milestone.title}</p><p className="mt-1 text-xs text-muted-foreground">{milestone.description || "No description"}</p></div>{project.canManage ? <Select value={milestone.status} onValueChange={(value) => value && run(updateMilestoneStatusAction(project.id, milestone.id, value as typeof milestone.status), "Milestone updated")}><SelectTrigger className="h-8 w-32 text-xs"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(MILESTONE_LABEL).map(([value,label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select> : <Badge>{MILESTONE_LABEL[milestone.status]}</Badge>}</div><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span>Due {date(milestone.dueDate)}</span><span>{milestone.owner?.name || "No owner"}</span></div></div></div>) : <Empty text="Build the project flow by adding the first milestone." />}</div></Panel></TabsContent>

        <TabsContent value="resources"><Panel title="Files & Links" description="Shared references, documents and links for this project." action={<div className="flex gap-2"><Button variant="outline" onClick={() => setDialog("link")}><Link2 className="h-4 w-4" /> Add Link</Button><Button onClick={() => setDialog("file")}><Upload className="h-4 w-4" /> Upload File</Button></div>}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{project.resources.map((resource) => <ResourceRow key={resource.id} resource={resource} />)}</div>{!project.resources.length && <Empty text="No files or links have been shared." />}</Panel></TabsContent>

        <TabsContent value="notes"><Panel title="Shared Notes" description="Lightweight project knowledge available to authorized members." action={<Button onClick={() => { setNoteForm({ id: "", title: "", content: "" }); setDialog("note"); }}><Plus className="h-4 w-4" /> New Note</Button>}><div className="grid gap-3 lg:grid-cols-2">{project.notes.map((note) => <div key={note.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between"><div><h3 className="font-medium">{note.title}</h3><p className="mt-1 text-xs text-muted-foreground">{note.author.name} · updated {dateTime(note.updatedAt)}</p></div><DropdownMenu><DropdownMenuTrigger render={<Button size="icon" variant="ghost" />}><MoreHorizontal className="h-4 w-4" /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => editNote(note)}>Edit note</DropdownMenuItem><DropdownMenuItem className="text-destructive" onClick={() => run(archiveProjectNoteAction(project.id, note.id), "Note archived")}>Archive note</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><p className="mt-4 whitespace-pre-wrap text-sm text-muted-foreground">{note.content}</p></div>)}</div>{!project.notes.length && <Empty text="No notes yet." />}</Panel></TabsContent>

        <TabsContent value="conversations"><div className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="grid min-h-[560px] lg:grid-cols-[280px_1fr]"><aside className="border-b lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">Conversations</h2><p className="text-xs text-muted-foreground">Private to participants</p></div>{project.canManage && <Button size="icon" onClick={() => setDialog("conversation")}><Plus className="h-4 w-4" /></Button>}</div><div className="max-h-52 overflow-y-auto p-2 lg:max-h-[500px]">{project.conversations.map((conversation) => <button key={conversation.id} onClick={() => setSelectedConversationId(conversation.id)} className={cn("mb-1 w-full rounded-xl p-3 text-left", selectedConversation?.id === conversation.id ? "bg-primary/10" : "hover:bg-muted/50")}><p className="truncate text-sm font-medium">{conversationTitle(conversation)}</p><p className="mt-1 truncate text-xs text-muted-foreground">{conversation.messages.at(-1)?.content || "No messages yet"}</p></button>)}</div></aside><section className="flex min-w-0 flex-col">{selectedConversation ? <><header className="border-b p-4"><h2 className="font-semibold">{conversationTitle(selectedConversation)}</h2><p className="mt-0.5 text-xs text-muted-foreground">{selectedConversation.participants.map((p) => p.name).join(", ")}</p></header><div className="flex-1 space-y-3 overflow-y-auto bg-muted/15 p-4">{selectedConversation.messages.map((item) => { const own = item.sender.id === project.currentUserId; return <div key={item.id} className={cn("flex", own && "justify-end")}><div className={cn("max-w-[78%] rounded-2xl px-3.5 py-2.5", own ? "bg-primary text-primary-foreground" : "border bg-card")}><p className="text-[11px] font-medium opacity-70">{item.sender.name}</p><p className="mt-0.5 whitespace-pre-wrap text-sm">{item.content}</p><p className="mt-1 text-[10px] opacity-60">{dateTime(item.createdAt)}</p></div></div>})}</div><div className="flex gap-2 border-t p-3"><Input value={message} onChange={(e) => setMessage(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); } }} placeholder="Write a message..." /><Button size="icon" onClick={sendMessage} disabled={!message.trim() || pending}><Send className="h-4 w-4" /></Button></div></> : <div className="grid flex-1 place-items-center p-10 text-center"><div><MessageSquare className="mx-auto h-10 w-10 text-muted-foreground/40" /><p className="mt-3 font-medium">No conversation selected</p><p className="mt-1 text-sm text-muted-foreground">Create a 1:1 or selected-member group conversation.</p></div></div>}</section></div></div></TabsContent>
      </Tabs>

      <FormDialog open={dialog === "task"} onOpenChange={(v) => !v && setDialog(null)} title="Create Task" submit="Create Task" onSubmit={createTask} pending={pending}><div className="grid gap-4 sm:grid-cols-2"><Field label="Task title *"><Input value={taskForm.title} onChange={(e) => setTaskForm({ ...taskForm, title: e.target.value })} /></Field><Field label="Due date *"><Input type="date" value={taskForm.dueDate} onChange={(e) => setTaskForm({ ...taskForm, dueDate: e.target.value })} /></Field><div className="sm:col-span-2"><Field label="Description"><Textarea value={taskForm.description} onChange={(e) => setTaskForm({ ...taskForm, description: e.target.value })} /></Field></div><Field label="Priority"><Select value={taskForm.priority} onValueChange={(value) => value && setTaskForm({ ...taskForm, priority: value as typeof taskForm.priority })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["LOW","MEDIUM","HIGH"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field><Field label="Status"><Select value={taskForm.status} onValueChange={(value) => value && setTaskForm({ ...taskForm, status: value as typeof taskForm.status })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{TASK_COLUMNS.map((item) => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></Field><div className="sm:col-span-2"><MemberChecks users={project.members} selected={taskForm.assigneeIds} onChange={(assigneeIds) => setTaskForm({ ...taskForm, assigneeIds })} label="Assignees *" /></div><div className="sm:col-span-2"><Field label="Checklist (one item per line)"><Textarea rows={4} value={taskForm.checklist} onChange={(e) => setTaskForm({ ...taskForm, checklist: e.target.value })} /></Field></div></div></FormDialog>

      <FormDialog open={dialog === "milestone"} onOpenChange={(v) => !v && setDialog(null)} title="Add Milestone" submit="Add Milestone" onSubmit={() => run(createMilestoneAction(project.id, milestoneForm), "Milestone added")} pending={pending}><div className="space-y-4"><Field label="Title *"><Input value={milestoneForm.title} onChange={(e) => setMilestoneForm({ ...milestoneForm, title: e.target.value })} /></Field><Field label="Description"><Textarea value={milestoneForm.description} onChange={(e) => setMilestoneForm({ ...milestoneForm, description: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Start date"><Input type="date" value={milestoneForm.startDate} onChange={(e) => setMilestoneForm({ ...milestoneForm, startDate: e.target.value })} /></Field><Field label="Due date *"><Input type="date" value={milestoneForm.dueDate} onChange={(e) => setMilestoneForm({ ...milestoneForm, dueDate: e.target.value })} /></Field></div><Field label="Owner"><Select value={milestoneForm.ownerId} onValueChange={(value) => value && setMilestoneForm({ ...milestoneForm, ownerId: value })}><SelectTrigger className="w-full"><SelectValue placeholder="Select owner" /></SelectTrigger><SelectContent>{project.members.map((member) => <SelectItem key={member.id} value={member.id}>{member.name}</SelectItem>)}</SelectContent></Select></Field></div></FormDialog>

      <FormDialog open={dialog === "link"} onOpenChange={(v) => !v && setDialog(null)} title="Add Link" submit="Add Link" onSubmit={() => run(addProjectLinkAction(project.id, resourceForm), "Link added")} pending={pending}><div className="space-y-4"><Field label="Title"><Input value={resourceForm.title} onChange={(e) => setResourceForm({ ...resourceForm, title: e.target.value })} /></Field><Field label="URL *"><Input type="url" placeholder="https://" value={resourceForm.url} onChange={(e) => setResourceForm({ ...resourceForm, url: e.target.value })} /></Field><Field label="Note"><Textarea value={resourceForm.note} onChange={(e) => setResourceForm({ ...resourceForm, note: e.target.value })} /></Field></div></FormDialog>

      <FormDialog open={dialog === "file"} onOpenChange={(v) => !v && setDialog(null)} title="Upload File" submit="Upload File" onSubmit={uploadFile} pending={pending}><div className="space-y-4"><input ref={fileInput} type="file" className="hidden" onChange={(e) => setFileForm({ ...fileForm, file: e.target.files?.[0] ?? null })} /><button type="button" onClick={() => fileInput.current?.click()} className="flex w-full flex-col items-center rounded-xl border border-dashed p-8 hover:bg-muted/30"><Upload className="h-7 w-7 text-primary" /><p className="mt-2 text-sm font-medium">{fileForm.file?.name || "Choose a supported file"}</p><p className="text-xs text-muted-foreground">Images, PDF, Office files, text or ZIP</p></button><Field label="Display title"><Input value={fileForm.title} onChange={(e) => setFileForm({ ...fileForm, title: e.target.value })} /></Field><Field label="Note"><Textarea value={fileForm.note} onChange={(e) => setFileForm({ ...fileForm, note: e.target.value })} /></Field></div></FormDialog>

      <FormDialog open={dialog === "note"} onOpenChange={(v) => !v && setDialog(null)} title={noteForm.id ? "Edit Note" : "New Note"} submit={noteForm.id ? "Save Changes" : "Add Note"} onSubmit={() => run(noteForm.id ? updateProjectNoteAction(project.id, noteForm.id, noteForm) : createProjectNoteAction(project.id, noteForm), noteForm.id ? "Note updated" : "Note added")} pending={pending}><div className="space-y-4"><Field label="Title *"><Input value={noteForm.title} onChange={(e) => setNoteForm({ ...noteForm, title: e.target.value })} /></Field><Field label="Note *"><Textarea rows={8} value={noteForm.content} onChange={(e) => setNoteForm({ ...noteForm, content: e.target.value })} /></Field></div></FormDialog>

      <FormDialog open={dialog === "conversation"} onOpenChange={(v) => !v && setDialog(null)} title="New Conversation" submit="Create Conversation" onSubmit={() => run(createProjectConversationAction(project.id, conversationForm), "Conversation created")} pending={pending}><div className="space-y-4"><Field label="Group name (optional)"><Input value={conversationForm.name} onChange={(e) => setConversationForm({ ...conversationForm, name: e.target.value })} /></Field><Field label="Related task (optional)"><Select value={conversationForm.taskId || "none"} onValueChange={(value) => value && setConversationForm({ ...conversationForm, taskId: value === "none" ? "" : value })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No linked task</SelectItem>{project.tasks.map((task) => <SelectItem key={task.id} value={task.id}>{task.title}</SelectItem>)}</SelectContent></Select></Field><MemberChecks users={project.members.filter((member) => member.id !== project.currentUserId)} selected={conversationForm.participantIds} onChange={(participantIds) => setConversationForm({ ...conversationForm, participantIds })} label="Participants *" /></div></FormDialog>

      <FormDialog open={dialog === "team"} onOpenChange={(v) => !v && setDialog(null)} title="Manage Project Team" submit="Save Team" onSubmit={() => run(updateProjectTeamAction(project.id, teamForm.headUserId, teamForm.memberIds), "Team updated")} pending={pending}><div className="space-y-4"><Field label="Project head"><Select value={teamForm.headUserId} onValueChange={(value) => value && setTeamForm({ ...teamForm, headUserId: value })}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{project.availableUsers.map((user) => <SelectItem key={user.id} value={user.id}>{user.name} · {user.role.toLowerCase()}</SelectItem>)}</SelectContent></Select></Field><MemberChecks users={project.availableUsers} selected={teamForm.memberIds} onChange={(memberIds) => setTeamForm({ ...teamForm, memberIds })} label="Team members" /></div></FormDialog>
    </div>
  );
}

function TaskCard({ task, canManage, onEdit, onStatus, onArchive, onChecklist }: { task: ProjectWorkspaceRecord["tasks"][number]; canManage: boolean; onEdit: () => void; onStatus: (status: "NOT_STARTED" | "IN_PROGRESS" | "REVIEW" | "COMPLETED") => void; onArchive: () => void; onChecklist: (id: string) => void }) {
  return <div className="rounded-xl border bg-card p-3 shadow-sm"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><p className={cn("text-sm font-medium", task.status === "COMPLETED" && "text-muted-foreground line-through")}>{task.title}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{task.description}</p></div><DropdownMenu><DropdownMenuTrigger render={<Button size="icon" variant="ghost" className="h-7 w-7" />}><MoreHorizontal className="h-4 w-4" /></DropdownMenuTrigger><DropdownMenuContent align="end">{canManage && <DropdownMenuItem onClick={onEdit}>Edit task</DropdownMenuItem>}{TASK_COLUMNS.filter((item) => item.value !== task.status).map((item) => <DropdownMenuItem key={item.value} onClick={() => onStatus(item.value)}>Move to {item.label}</DropdownMenuItem>)}{canManage && <DropdownMenuItem className="text-destructive" onClick={onArchive}>Archive task</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></div><div className="mt-3 flex items-center justify-between text-[11px] text-muted-foreground"><span>{date(task.dueDate)}</span><Badge variant="outline" className="text-[9px]">{task.priority.toLowerCase()}</Badge></div>{task.checklist.length > 0 && <div className="mt-3 space-y-1.5 border-t pt-2">{task.checklist.map((item) => <button key={item.id} onClick={() => onChecklist(item.id)} className="flex w-full items-center gap-2 text-left text-[11px]"><span className={cn("grid h-3.5 w-3.5 place-items-center rounded border", item.completed && "border-primary bg-primary text-primary-foreground")}>{item.completed && <Check className="h-2.5 w-2.5" />}</span><span className={cn(item.completed && "line-through text-muted-foreground")}>{item.title}</span></button>)}</div>}<div className="mt-3 flex -space-x-1.5">{task.assignees.map((member) => <Avatar key={member.id} name={member.name} small />)}</div></div>;
}

function ResourceRow({ resource }: { resource: ProjectWorkspaceRecord["resources"][number] }) {
  const href = resource.type === "LINK" ? resource.url : resource.dataUrl;
  return <a href={href || undefined} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border bg-card p-3 hover:border-primary/25 hover:bg-muted/20"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary">{resource.type === "LINK" ? <Link2 className="h-4 w-4" /> : <File className="h-4 w-4" />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{resource.title}</span><span className="block truncate text-[11px] text-muted-foreground">{resource.addedBy.name} · {date(resource.createdAt)}</span></span><ExternalLink className="h-3.5 w-3.5 text-muted-foreground" /></a>;
}

function Panel({ title, description, action, children }: { title: string; description?: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border bg-card shadow-sm"><header className="flex items-center justify-between gap-4 border-b px-5 py-4"><div><h2 className="font-semibold">{title}</h2>{description && <p className="mt-0.5 text-xs text-muted-foreground">{description}</p>}</div>{action}</header><div className="p-5">{children}</div></section>; }
function MetaCard({ icon: Icon, label, value }: { icon: typeof CalendarDays; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-2xl border bg-card p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="truncate text-sm font-medium">{value}</p></div></div>; }
function Avatar({ name, small = false }: { name: string; small?: boolean }) { return <span title={name} className={cn("grid place-items-center rounded-full border-2 border-card bg-primary/10 font-semibold text-primary", small ? "h-6 w-6 text-[8px]" : "h-8 w-8 text-[10px]")}>{initials(name)}</span>; }
function Empty({ text }: { text: string }) { return <div className="py-8 text-center text-sm text-muted-foreground">{text}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label className="text-xs">{label}</Label>{children}</div>; }
function MemberChecks({ users, selected, onChange, label }: { users: ProjectWorkspaceRecord["members"]; selected: string[]; onChange: (ids: string[]) => void; label: string }) { return <div><Label className="text-xs">{label}</Label><div className="mt-2 grid max-h-44 grid-cols-2 gap-2 overflow-y-auto rounded-xl border p-3">{users.map((user) => <label key={user.id} className="flex cursor-pointer items-center gap-2 rounded-lg p-1.5 text-xs hover:bg-muted"><input type="checkbox" checked={selected.includes(user.id)} onChange={(e) => onChange(e.target.checked ? [...selected, user.id] : selected.filter((id) => id !== user.id))} />{user.name}</label>)}</div></div>; }
function FormDialog({ open, onOpenChange, title, submit, onSubmit, pending, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; submit: string; onSubmit: () => void; pending: boolean; children: React.ReactNode }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><div className="max-h-[65vh] overflow-y-auto py-2">{children}</div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={onSubmit} disabled={pending}>{submit}</Button></DialogFooter></DialogContent></Dialog>; }
function date(value: string) { return new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }); }
function dateTime(value: string) { return new Date(value).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }); }
