"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Clipboard, KeyRound, Loader2, Mail, MoreHorizontal, Plus, Search, ShieldCheck, UserCheck, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PERMISSION_GROUPS, ROLE_PRESETS, type TeamRoleKey } from "@/lib/team-permissions";
import { cancelInviteAction, inviteTeamMemberAction, regenerateInviteAction, removeMemberAction, setMemberStatusAction, updateMemberAction } from "@/services/team-management";

type Data = NonNullable<Awaited<ReturnType<typeof import("@/services/team-management").getTeamManagementData>>>;
type Member = Data["members"][number];
type Invite = Data["invites"][number];
const roleEntries = Object.entries(ROLE_PRESETS).filter(([key]) => key !== "OWNER") as [string, { readonly name: string; readonly department: string; readonly permissions: readonly string[] }][];

function initials(name: string) { return name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)); }

export function TeamManagementClient({ initialData }: { initialData: Data }) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [inviteOpen, setInviteOpen] = useState(false);
  const [editing, setEditing] = useState<Member | null>(null);
  const [activation, setActivation] = useState<{ link: string; existing: boolean } | null>(null);
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const filtered = useMemo(() => initialData.members.filter((member) => {
    const text = `${member.user.name} ${member.user.email} ${member.roleName} ${member.department ?? ""}`.toLowerCase();
    return text.includes(search.toLowerCase()) && (roleFilter === "all" || member.roleKey === roleFilter) && (statusFilter === "all" || member.status === statusFilter);
  }), [initialData.members, roleFilter, search, statusFilter]);

  function run(action: Promise<{ success: boolean; error?: string; data?: unknown }>, success: string) {
    startTransition(async () => { const result = await action; if (!result.success) { toast.error(result.error); return; } toast.success(success); router.refresh(); });
  }

  return <div className="mx-auto max-w-[1500px] space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Company workspace</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Team Management</h1><p className="mt-1 text-sm text-muted-foreground">Manage team members, roles and workspace access.</p></div>
      <Button className="gap-2" onClick={() => setInviteOpen(true)}><Plus className="h-4 w-4" /> Invite Member</Button>
    </div>

    <div className="rounded-2xl border bg-card p-5 shadow-sm">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{initialData.stats.usedSeats} of {initialData.workspace.seatLimit} seats used</p><p className="text-xs text-muted-foreground">Pending invitations reserve a seat until cancelled or expired.</p></div><span className="text-sm font-medium text-primary">{Math.round(initialData.stats.usedSeats / initialData.workspace.seatLimit * 100)}%</span></div>
      <div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.min(100, initialData.stats.usedSeats / initialData.workspace.seatLimit * 100)}%` }} /></div>
    </div>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Stat icon={Users} label="Used Seats" value={`${initialData.stats.usedSeats} / ${initialData.workspace.seatLimit}`} />
      <Stat icon={UserCheck} label="Active Members" value={initialData.stats.activeMembers} />
      <Stat icon={Mail} label="Pending Invites" value={initialData.stats.pendingInvites} />
      <Stat icon={KeyRound} label="Available Seats" value={initialData.stats.availableSeats} />
    </div>

    <Tabs defaultValue="members">
      <TabsList><TabsTrigger value="members">Members</TabsTrigger><TabsTrigger value="invitations">Invitations <Badge variant="secondary" className="ml-2">{initialData.stats.pendingInvites}</Badge></TabsTrigger><TabsTrigger value="roles">Roles & Access</TabsTrigger></TabsList>
      <TabsContent value="members" className="mt-5 space-y-4">
        <div className="grid gap-3 rounded-xl border bg-card p-3 md:grid-cols-[1fr_190px_160px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" placeholder="Search by member, email or department..." /></div><Select value={roleFilter} onValueChange={(v) => v && setRoleFilter(v)}><SelectTrigger><SelectValue placeholder="All roles" /></SelectTrigger><SelectContent><SelectItem value="all">All roles</SelectItem>{roleEntries.map(([key, role]) => <SelectItem key={key} value={key}>{role.name}</SelectItem>)}</SelectContent></Select><Select value={statusFilter} onValueChange={(v) => v && setStatusFilter(v)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="ACTIVE">Active</SelectItem><SelectItem value="INACTIVE">Inactive</SelectItem></SelectContent></Select></div>
        <div className="overflow-hidden rounded-xl border bg-card"><div className="hidden grid-cols-[minmax(240px,1.3fr)_1fr_1fr_110px_120px_48px] gap-4 border-b bg-muted/40 px-5 py-3 text-xs font-medium uppercase tracking-wider text-muted-foreground lg:grid"><span>Member</span><span>Role</span><span>Access</span><span>Projects</span><span>Status</span><span /></div>{filtered.map((member) => <MemberRow key={member.id} member={member} busy={pending} onEdit={() => setEditing(member)} onStatus={(active) => run(setMemberStatusAction(member.id, active), active ? "Member reactivated" : "Member deactivated")} onRemove={() => run(removeMemberAction(member.id), "Workspace access removed")} />)}{!filtered.length && <div className="p-10 text-center text-sm text-muted-foreground">No members match these filters.</div>}</div>
      </TabsContent>
      <TabsContent value="invitations" className="mt-5"><div className="overflow-hidden rounded-xl border bg-card">{initialData.invites.length ? initialData.invites.map((invite) => <InviteRow key={invite.id} invite={invite} busy={pending} onRegenerate={() => startTransition(async () => { const result = await regenerateInviteAction(invite.id); if (!result.success) { toast.error(result.error); return; } setActivation({ link: makeInviteLink(result.data.token, result.data.existingUser), existing: result.data.existingUser }); toast.success("A new secure invitation link was generated"); router.refresh(); })} onCancel={() => run(cancelInviteAction(invite.id), "Invitation cancelled")} />) : <div className="p-10 text-center"><Mail className="mx-auto h-8 w-8 text-muted-foreground/50" /><p className="mt-3 text-sm text-muted-foreground">No invitations yet.</p></div>}</div></TabsContent>
      <TabsContent value="roles" className="mt-5"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roleEntries.map(([key, role]) => <div key={key} className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between"><div><h3 className="font-medium">{role.name}</h3><p className="text-xs text-muted-foreground">{role.department}</p></div><ShieldCheck className="h-5 w-5 text-primary" /></div><div className="mt-4 flex flex-wrap gap-1.5">{role.permissions.slice(0, 6).map((permission) => <Badge variant="secondary" key={permission} className="font-normal">{permission.split(".").join(" · ")}</Badge>)}{role.permissions.length > 6 && <Badge variant="outline">+{role.permissions.length - 6}</Badge>}</div></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Preset roles provide defaults. Every member&apos;s permissions can be overridden from Edit role & access. Custom role names are supported per member.</p></TabsContent>
    </Tabs>
    <InviteDialog open={inviteOpen} onOpenChange={setInviteOpen} busy={pending} onCreated={(token, existing) => { setInviteOpen(false); setActivation({ link: makeInviteLink(token, existing), existing }); router.refresh(); }} />
    {editing && <AccessDialog member={editing} busy={pending} onClose={() => setEditing(null)} onSave={(input) => startTransition(async () => { const result = await updateMemberAction(editing.id, input); if (!result.success) { toast.error(result.error); return; } toast.success("Role and access updated"); setEditing(null); router.refresh(); })} />}
    <ActivationDialog value={activation} onClose={() => setActivation(null)} />
  </div>;
}

function makeInviteLink(token: string, existing: boolean) { return `${window.location.origin}${existing ? "/accept-team-invite" : "/reset-password"}?token=${token}`; }
function Stat({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: string | number }) { return <div className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">{label}</p><div className="rounded-lg bg-primary/10 p-2"><Icon className="h-4 w-4 text-primary" /></div></div><p className="mt-2 text-2xl font-semibold tabular-nums">{value}</p></div>; }

function MemberRow({ member, busy, onEdit, onStatus, onRemove }: { member: Member; busy: boolean; onEdit(): void; onStatus(active: boolean): void; onRemove(): void }) { return <div className="grid gap-4 border-b px-4 py-4 last:border-b-0 lg:grid-cols-[minmax(240px,1.3fr)_1fr_1fr_110px_120px_48px] lg:items-center lg:px-5"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-sm font-semibold text-primary">{initials(member.user.name)}</div><div className="min-w-0"><button className="truncate text-left font-medium hover:text-primary" onClick={onEdit}>{member.user.name}</button><p className="truncate text-xs text-muted-foreground">{member.user.email}</p></div></div><div><p className="text-sm font-medium">{member.roleName}</p><p className="text-xs text-muted-foreground">{member.department ?? "No department"}</p></div><div><p className="text-sm">{member.isOwner ? "Full access" : `${member.permissions.length} permissions`}</p><p className="text-xs text-muted-foreground">{member.isOwner ? "Protected owner" : "Custom access"}</p></div><div><p className="text-sm text-muted-foreground">—</p></div><Badge variant={member.status === "ACTIVE" ? "default" : "secondary"} className="w-fit">{member.status === "ACTIVE" ? "Active" : "Inactive"}</Badge><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" disabled={busy} aria-label={`Actions for ${member.user.name}`} />}><MoreHorizontal className="h-4 w-4" /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}>Edit role & access</DropdownMenuItem>{!member.isOwner && <><DropdownMenuItem onClick={() => onStatus(member.status !== "ACTIVE")}>{member.status === "ACTIVE" ? "Deactivate access" : "Reactivate access"}</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-destructive" onClick={onRemove}>Remove from team</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>; }

function InviteRow({ invite, busy, onRegenerate, onCancel }: { invite: Invite; busy: boolean; onRegenerate(): void; onCancel(): void }) { return <div className="flex flex-col gap-4 border-b p-4 last:border-b-0 sm:flex-row sm:items-center"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted text-sm font-semibold">{initials(invite.name)}</div><div className="min-w-0 flex-1"><p className="font-medium">{invite.name}</p><p className="truncate text-xs text-muted-foreground">{invite.email}</p></div><div className="sm:w-44"><p className="text-sm">{invite.roleName}</p><p className="text-xs text-muted-foreground">Invited {formatDate(invite.createdAt)}</p></div><div className="sm:w-32"><Badge variant={invite.status === "PENDING" ? "default" : "secondary"}>{invite.status.toLowerCase()}</Badge><p className="mt-1 text-[11px] text-muted-foreground">Expires {formatDate(invite.expiresAt)}</p></div>{invite.status === "PENDING" && <div className="flex gap-2"><Button size="sm" variant="outline" disabled={busy} onClick={onRegenerate}>Regenerate</Button><Button size="sm" variant="ghost" disabled={busy} onClick={onCancel}>Cancel</Button></div>}</div>; }

type AccessInput = { roleKey: string; roleName: string; department?: string; permissions: string[] };
function PermissionEditor({ permissions, setPermissions }: { permissions: string[]; setPermissions(value: string[]): void }) { const all = PERMISSION_GROUPS.flatMap((g) => g.permissions.map(([key]) => key)); return <div className="space-y-4"><div className="flex items-center justify-between"><Label>Permissions / Access</Label><div className="flex gap-1"><Button type="button" variant="ghost" size="sm" onClick={() => setPermissions(all)}>Select all</Button><Button type="button" variant="ghost" size="sm" onClick={() => setPermissions([])}>Clear all</Button></div></div><div className="max-h-[340px] space-y-4 overflow-y-auto rounded-xl border p-4">{PERMISSION_GROUPS.map((group) => <div key={group.label}><p className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{group.label}</p><div className="grid gap-2 sm:grid-cols-2">{group.permissions.map(([key, label]) => <label key={key} className="flex cursor-pointer items-start gap-2 rounded-lg border p-2.5 text-sm hover:bg-muted/40"><input type="checkbox" className="mt-0.5 accent-primary" checked={permissions.includes(key)} onChange={(e) => setPermissions(e.target.checked ? [...permissions, key] : permissions.filter((item) => item !== key))} /><span>{label}</span></label>)}</div></div>)}</div></div>; }

function RoleFields({ value, onChange }: { value: AccessInput; onChange(value: AccessInput): void }) { function selectRole(key: string | null) { if (!key) return; if (key === "CUSTOM") return onChange({ ...value, roleKey: key, roleName: "", permissions: [] }); const role = ROLE_PRESETS[key as TeamRoleKey]; onChange({ roleKey: key, roleName: role.name, department: role.department, permissions: [...role.permissions] }); } return <><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Role *</Label><Select value={value.roleKey} onValueChange={selectRole}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{roleEntries.map(([key, role]) => <SelectItem key={key} value={key}>{role.name}</SelectItem>)}<SelectItem value="CUSTOM">Custom role</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label>Department</Label><Input value={value.department ?? ""} onChange={(e) => onChange({ ...value, department: e.target.value })} placeholder="e.g. Engineering" /></div></div>{value.roleKey === "CUSTOM" && <div className="space-y-1.5"><Label>Custom role name *</Label><Input value={value.roleName} onChange={(e) => onChange({ ...value, roleName: e.target.value })} placeholder="e.g. Senior Fashion Designer" /></div>}<PermissionEditor permissions={value.permissions} setPermissions={(permissions) => onChange({ ...value, permissions })} /></>; }

function InviteDialog({ open, onOpenChange, busy, onCreated }: { open: boolean; onOpenChange(v: boolean): void; busy: boolean; onCreated(token: string, existing: boolean): void }) { const first = roleEntries[0]; const [form, setForm] = useState({ name: "", email: "", message: "", roleKey: first[0], roleName: first[1].name, department: first[1].department, permissions: [...first[1].permissions] as string[] }); async function submit() { const result = await inviteTeamMemberAction(form); if (!result.success) return toast.error(result.error); toast.success("Invitation created"); onCreated(result.data.token, result.data.existingUser); } return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Invite Team Member</DialogTitle><DialogDescription>They will use their own SupplyBase login. Pending invitations reserve one workspace seat.</DialogDescription></DialogHeader><div className="space-y-5 py-2"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Full name *</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div><div className="space-y-1.5"><Label>Email *</Label><Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div></div><RoleFields value={form} onChange={(access) => setForm({ ...form, ...access })} /><div className="space-y-1.5"><Label>Optional message</Label><textarea className="min-h-20 w-full rounded-lg border bg-background px-3 py-2 text-sm" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Welcome note or onboarding context..." /></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={busy || !form.name || !form.email || !form.roleName || !form.permissions.length} onClick={submit}>{busy && <Loader2 className="h-4 w-4 animate-spin" />} Send Invite</Button></DialogFooter></DialogContent></Dialog>; }

function AccessDialog({ member, busy, onClose, onSave }: { member: Member; busy: boolean; onClose(): void; onSave(value: AccessInput): void }) { const [form, setForm] = useState<AccessInput>({ roleKey: member.roleKey, roleName: member.roleName, department: member.department ?? "", permissions: member.permissions }); return <Dialog open onOpenChange={(v) => !v && onClose()}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Edit role & access</DialogTitle><DialogDescription>{member.user.name} · Changes apply on the next server request.</DialogDescription></DialogHeader><div className="space-y-5 py-2"><RoleFields value={form} onChange={setForm} /></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy || !form.roleName} onClick={() => onSave(form)}>{busy && <Loader2 className="h-4 w-4 animate-spin" />} Save changes</Button></DialogFooter></DialogContent></Dialog>; }

function ActivationDialog({ value, onClose }: { value: { link: string; existing: boolean } | null; onClose(): void }) { async function copy() { if (!value) return; await navigator.clipboard.writeText(value.link); toast.success("Invitation link copied"); } return <Dialog open={Boolean(value)} onOpenChange={(v) => !v && onClose()}><DialogContent><DialogHeader><DialogTitle>Invitation created</DialogTitle><DialogDescription>Email delivery is not configured. Copy and send this secure, one-time link manually.</DialogDescription></DialogHeader>{value && <div className="space-y-3"><div className="rounded-xl border bg-muted/40 p-3"><p className="break-all font-mono text-xs">{value.link}</p></div><p className="text-xs text-muted-foreground">{value.existing ? "This email already has a SupplyBase account. They must sign in with that account and confirm the invitation." : "The member will set their own password. The link expires in 24 hours and can only be used once."}</p></div>}<DialogFooter><Button variant="outline" onClick={onClose}>Done</Button><Button onClick={copy}><Clipboard className="h-4 w-4" /> Copy Invite Link</Button></DialogFooter></DialogContent></Dialog>; }
